packages:
  - extension-tools
  - global
  - mcp-react-config
  - react-webmcp
  - smart-dom-reader
  - smart-dom-reader/mcp-server
  - transports
  - webmcp-ts-sdk
  - e2e
  - e2e/test-app
  - e2e/react-webmcp-test-app
  - e2e/mcp-react-config-test-app
  - e2e/web-standards-showcase
  - e2e/mcp-ui-with-webmcp/**

catalog:
  '@cloudflare/vite-plugin': ^1.13.18
  '@composio/json-schema-to-zod': ^0.1.17
  '@hookform/resolvers': ^5.2.2
  '@modelcontextprotocol/sdk': 1.15.0
  '@radix-ui/react-collapsible': ^1.1.12
  '@sentry/cloudflare': ^10.22.0
  '@sentry/react': ^10.22.0
  '@sentry/vite-plugin': ^4.6.0
  '@types/chrome': ^0.0.326
  '@types/node': 22.17.2
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@use-gesture/react': ^10.3.1
  ai: ^5.0.83
  babel-plugin-react-compiler: ^1.0.0
  react: ^19.1.0
  react-dom: ^19.1.0
  react-markdown: ^10.1.0
  tsdown: ^0.15.10
  tsx: ^4.20.0
  typescript: ^5.8.3
  vite: ^7.1.12
  vite-plugin-monkey: ^6.0.1
  wrangler: ^4.45.3
  zod: 3.25.76

onlyBuiltDependencies:
  - '@axodotdev/oranda'
  - '@tailwindcss/oxide'
  - dtrace-provider
  - esbuild
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd
