packages:
  - packages/*
  - packages/smart-dom-reader/mcp-server
  - skills/webmcp-setup
  - e2e
  - e2e/test-app
  - e2e/react-webmcp-test-app
  - e2e/web-standards-showcase

catalog:
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
  '@vitest/coverage-v8': ^4.0.18
  playwright: ^1.58.0
  '@cloudflare/vite-plugin': ^1.13.18
  '@composio/json-schema-to-zod': ^0.1.17
  '@hookform/resolvers': ^5.2.2
  '@modelcontextprotocol/sdk': 1.25.2
  '@radix-ui/react-collapsible': ^1.1.12
  '@sentry/cloudflare': ^10.22.0
  '@sentry/react': ^10.22.0
  '@sentry/vite-plugin': ^4.6.0
  '@types/chrome': ^0.1.36
  '@types/node': 22.19.7
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  '@use-gesture/react': ^10.3.1
  ai: ^5.0.83
  babel-plugin-react-compiler: ^1.0.0
  react: ^19.1.0
  react-dom: ^19.1.0
  react-markdown: ^10.1.0
  tsdown: ^0.15.10
  tsx: ^4.20.0
  typescript: ^5.8.3
  vite: ^7.1.2
  vite-plugin-monkey: ^6.0.1
  vitest: ^4.0.18
  wrangler: ^4.45.3
  zod: 4.3.5

onlyBuiltDependencies:
  - '@axodotdev/oranda'
  - '@tailwindcss/oxide'
  - dtrace-provider
  - esbuild
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd
