packages:
  - "extension-tools"
  - "global"
  - "mcp-react-hook-form"
  - "mcp-react-hooks"
  - "transports"

catalog:
  typescript: ^5.8.3
  "@types/node": ^22.15.21
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
  "@types/chrome": ^0.0.326
  tsup: ^8.4.0
  tsx: ^4.20.0
  "@modelcontextprotocol/sdk": 1.15.0
  zod: 3.24.1
  react: ^19.1.0
  react-dom: ^19.1.0

onlyBuiltDependencies:
  - "@axodotdev/oranda"
  - "@tailwindcss/oxide"
  - dtrace-provider
  - esbuild
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd