name: Bug Report
description: Report a bug in one of the @mcp-b packages
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is this bug related to?
      options:
        - "@mcp-b/transports"
        - "@mcp-b/global"
        - "@mcp-b/react-webmcp"
        - "@mcp-b/webmcp-ts-sdk"
        - "@mcp-b/chrome-devtools-mcp"
        - "@mcp-b/extension-tools"
        - "@mcp-b/mcp-iframe"
        - "@mcp-b/smart-dom-reader"
        - "@webmcp/helpers"
        - "Other / Multiple"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install package...
        2. Call function...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: If applicable, add a minimal code example that reproduces the issue.
      render: typescript
      placeholder: |
        import { something } from '@mcp-b/package';

        // Your code here

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details.
      placeholder: |
        - OS: macOS 14.0
        - Node.js: 22.12.0
        - Browser: Chrome 120 (if applicable)
        - Framework: React 18, Next.js 14 (if applicable)
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
