name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is this feature related to?
      options:
        - "@mcp-b/transports"
        - "@mcp-b/global"
        - "@mcp-b/react-webmcp"
        - "@mcp-b/webmcp-ts-sdk"
        - "@mcp-b/chrome-devtools-mcp"
        - "@mcp-b/extension-tools"
        - "@mcp-b/mcp-iframe"
        - "@mcp-b/smart-dom-reader"
        - "@webmcp/helpers"
        - "New package"
        - "Other / Multiple"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I also considered...
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Example API / Usage
      description: If applicable, show how you'd like to use this feature.
      render: typescript
      placeholder: |
        // Example of how you'd like to use this feature
        import { newFeature } from '@mcp-b/package';

        newFeature({
          option: 'value'
        });

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here.
    validations:
      required: false
