/** Risk level for a tool call, used to select default approval behaviour. */
export type RiskLevel = 'low' | 'medium' | 'high';

/**
 * Machine-readable metadata attached to every guarded tool registration.
 *
 * This data serves two purposes:
 * 1. It is mapped to MCP `ToolAnnotations` so native agent runtimes that
 *    already have their own approval UI (e.g. the MCP-B Agent extension) receive
 *    real signal rather than empty hints.
 * 2. It drives the on-page {@link ConsentBroker} when no native gate is present.
 */
export interface ConsentMetadata {
  /**
   * Human-readable capability scopes, e.g. `['read:deployments', 'write:rollback']`.
   * Shown verbatim in the consent card.
   */
  scope: string[];
  /**
   * Whether the action can be undone. Irreversible actions can never be
   * session-pre-approved; the user must confirm every call.
   */
  reversible: boolean;
  /** Broad risk bucket. Drives default annotation mapping and card styling. */
  riskLevel: RiskLevel;
  /**
   * Static flag (`true` always prompts, `false` auto-approves), or a predicate
   * over the actual call arguments for argument-dependent risk (e.g. only
   * prompt when `rollback.force === true`).
   */
  requiresApproval: boolean | ((args: unknown) => boolean);
  /**
   * When true, approval requires a WebAuthn user-verification ceremony
   * (platform authenticator: Touch ID, Windows Hello, hardware key),
   * not just a DOM click. Falls back to a standard click when no platform
   * authenticator is available, so the demo doesn't hard-block on
   * unsupported hardware. Recommended for irreversible, high-risk tools.
   */
  requireUserPresence?: boolean;
}

/** The resolution of a pending consent prompt. */
export interface ConsentDecision {
  /** Whether the user (or the session-preapproval cache) approved the call. */
  approved: boolean;
  /**
   * How the decision was reached:
   * - `'user'` — explicit button press in the consent card
   * - `'timeout'` — 30-second guard elapsed with no response (auto-deny)
   * - `'session-preapproval'` — the tool+origin pair was pre-approved earlier
   *   in this session and `consent.reversible` is `true`
   */
  reason?: 'user' | 'timeout' | 'session-preapproval' | 'presence-lockout' | 'rate-limited';
}

/**
 * An in-flight approval request sitting in the broker queue.
 * The consent card UI renders one card per entry in the pending list.
 */
export interface PendingConsentRequest {
  /** UUID generated by the broker for this specific invocation. */
  id: string;
  /** Registered tool name, e.g. `'rollbackDeployment'`. */
  toolName: string;
  /** Page origin that registered the tool, e.g. `'https://app.example.com'`. */
  origin: string;
  /** Raw arguments passed by the MCP client for this invocation. */
  args: unknown;
  /** Consent metadata declared when the tool was registered. */
  consent: ConsentMetadata;
  /** `Date.now()` at the moment the request entered the queue. */
  createdAt: number;
}
